name: Setup CI
on:
  push:
    paths:
      - ".upptimerc.yml"
  repository_dispatch:
    types: [setup]
  workflow_dispatch:
jobs:
  release:
    name: Setup Upptime
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ref: ${{ github.head_ref }}
      - name: Update template
        uses: upptime/uptime-monitor@v1.41.0
          command: "update-template"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
      - name: Update response time
        uses: upptime/uptime-monitor@v1.41.0
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Update summary in README
        uses: upptime/uptime-monitor@v1.41.0
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
      - name: Generate graphs
        uses: benc-uk/workflow-dispatch@v1
          workflow: Graphs CI
      - name: Generate site
        uses: upptime/uptime-monitor@v1.41.0
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
      - uses: peaceiris/actions-gh-pages@v4
        name: GitHub Pages Deploy
          publish_dir: "site/status-page/__sapper__/export/"
          force_orphan: "false"
          user_name: "github-actions[bot]"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
